name: LuckyWarsDoDo
main: KaitoDoDo\LuckyWars\LuckyWars
author: KaitoDoDo
version: 2.0.0 Subnor
api: [1.0.0, 2.0.0]

commands:
    lw:
        usage: /lw <leave-make>
        description: LuckyWars-Commands
    lwstart:
        usage: /lwstart
        description: LuckyWars-Force start